OT_book_list = ['Genesis',
            'Exodus',
            'Leviticus',
            'Numbers',
            'Deuteronomy',
            'Joshua',
            'Judges',
            'Ruth',
            '1 Samuel',
            '2 Samuel',
            '1 Kings',
            '2 Kings',
            '1 Chronicles',
            '2 Chronicles',
            'Ezra',
            'Esther',
            'Nehemiah',
            'Job',
            'Psalms',
            'Proverbs',
            'Ecclesiastes',
            'Song of Solomon',
            'Isaiah',
            'Jeremiah',
            'Lamentations',
            'Ezekiel',
            'Daniel',
            'Hosea',
            'Joel',
            'Amos',
            'Obadiah',
            'Jonah',
            'Micah',
            'Nahum',
            'Habakkuk',
            'Zephaniah',
            'Haggai',
            'Zechariah',
            'Malachi']
NT_book_list = ['Matthew',
            'Mark',
            'Luke',
            'John',
            'Acts',
            'Romans',
            '1 Corinthians',
            '2 Corinthians',
            'Galatians',
            'Ephesians',
            'Philippians',
            'Colossians',
            '1 Thessalonians',
            '2 Thessalonians',
            '1 Timothy',
            '2 Timothy',
            'Titus',
            'Philemon',
            'Hebrews',
            'James',
            '1 Peter',
            '2 Peter',
            '1 John',
            '2 John',
            '3 John',
            'Jude',
            'Revelation']
LXX_book_list = [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua (Alexandrinus)',
    'Joshua (Vaticanus)',
    'Judges (Alexandrinus)',
    'Judges (Vaticanus)',
    'Ruth',
    '1 Kingdoms (1 Samuel)',
    '2 Kingdoms (2 Samuel)',
    '3 Kingdoms (1 Kings)',
    '4 Kingdoms (2 Kings)',
    '1 Chronicles',
    '2 Chronicles',
    '1 Esdras',
    '2 Esdras (Ezra-Nehemiah)',
    'Esther',
    'Judith',
    'Tobit (Alexandrian)',
    'Tobit (Sinaiticus)',
    '1 Maccabees',
    '2 Maccabees',
    '3 Maccabees',
    '4 Maccabees',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song of Solomon',
    'Job',
    'Wisdom of Solomon',
    'Sirach',
    'Psalms of Solomon',
    'Isaiah',
    'Jeremiah',
    'Ezekiel',
    'Daniel (OG)',
    'Daniel (Theodotion)',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
    'Baruch',
    'Epistle of Jeremiah',
    'Lamentations',
    'Bel (Old Greek)',
    'Bel (Theodotion)',
    'Susanna (OG)',
    'Susanna (Theodotion)',
    'Odes'
]

whole_bible_list = OT_book_list + NT_book_list

skip_list = ['Matthew 17:21', 'Matthew 18:11', 'Matthew 23:14',
            'Mark 7:16', 'Mark 9:44', 'Mark 9:46',
            'Mark 11:26', 'Mark 15:28', 'Luke 17:36',
            'John 5:4', 'Acts 8:37', 'Acts 15:34',
            'Acts 24:7', 'Acts 28:29', 'Romans 16:24']